version: '3.8'

services:
    web:
        build: 
            context: ./services/web
        expose:
            - 5000
    api:
        build: 
            context: ./services/api
        expose:
            - 5000
    nginx:
        build: 
            context: ./services/nginx
        ports:
            - 80:80
        depends_on: 
            - web
